### ISSUE TITLE
Ambiguous case: facing quads

### ISSUE THREAD

**Issue by hidemat** [BorisTheBrave/mc-dc#1]
Hi Boris. First of all thanks for your tutorial. Thanks to you I was able to start my own implementation of the marching cubes algorithm in the Godot Engine.

However I don't know how to deal with this case:
<img width="128" alt="Screen Shot 2019-04-15 at 9 53 35 PM" src="https://user-images.githubusercontent.com/6559151/56181075-3d1eba80-5fc9-11e9-8962-7509f1c6feeb.png">

It works ok if I don't use inverse cases:
<img width="1053" alt="Screen Shot 2019-04-15 at 10 00 16 PM" src="https://user-images.githubusercontent.com/6559151/56181272-fe3d3480-5fc9-11e9-879f-2450fc06cc39.png">

But if I invert the values of the vertices I get the ambiguos cases:
<img width="1130" alt="Screen Shot 2019-04-15 at 10 00 49 PM" src="https://user-images.githubusercontent.com/6559151/56181296-1ad96c80-5fca-11e9-98a8-6a2c2405297b.png">

Is there a way to fix this or should I just give up and move on to dual contouring?

**Comment by BorisTheBrave** [comment]
I will take a look when I have some time over the weekend.

**Comment by hidemat** [comment]
Thanks. Best of luck friend.

**Comment by hidemat** [comment]
Oh I figured it out! I had to check the neighboring blocks and assign a Case A or Case B depending on the value of the neighbors, for this case I just had to check for 4 adjacent neighbors: front, back, left, right. Here are the results:

Without inverting:
<img width="899" alt="Screen Shot 2019-04-17 at 1 58 54 PM" src="https://user-images.githubusercontent.com/6559151/56317036-14a5d600-6119-11e9-9dbb-8f3d82d7adb4.png">

Inverting:
<img width="969" alt="Screen Shot 2019-04-17 at 1 11 55 PM" src="https://user-images.githubusercontent.com/6559151/56317054-1ff90180-6119-11e9-97b9-68c5f4c391d7.png">

**Comment by BorisTheBrave** [comment]
Hi hidemat, it shouldn't be necessary to check neighbouring blocks. It's a little hard to tell what is going on from your diagram - do you think you could submit a setup that causes the problem with the python in this repo?

I should say that the case you highlighted (4 solid points on two opposite edges) *never* needs inverting. You can simply rotate it instead.  I only use inverses where rotation doesn't work. [See here](https://github.com/BorisTheBrave/mc-dc/blob/master/marching_cubes_gen.py#L195)

**Comment by hidemat** [comment]
Yeah sorry for not explaining more clearly. I not very savvy with python so unfortunately I wasn't able to  implement it in python. I had to figure out how to do it in Godot so my code is significantly different from yours. I use 1 or 0 to determine if the vertex is solid or not. So I manually input the values for force certain scenarios to happen. I made 2 layers of this pattern to create what you see in the pictures:

<img width="481" alt="Screen Shot 2019-04-18 at 10 51 12 AM" src="https://user-images.githubusercontent.com/6559151/56377815-7ffab100-61c8-11e9-9a84-088d14ac2a3d.png">

So when the surrounding vertices are solid and the shape is not solid is where the issue was happening.

**Comment by BorisTheBrave** [comment]
I don't see any problems. I can create your shape, and I can invert solidity, and create a similar shape that way (note you have to flip the normals to get both looking correct, you don't seem to be doing that):

![image](https://user-images.githubusercontent.com/183773/56419955-0f20cb00-6294-11e9-9d69-0aa91b678c7e.png)

The differences is due to ambiguities in marching cubes, there's nothing in the algorithm to fix it. If you've found a solution that works for you, then great.

**Comment by hidemat** [comment]
I see. Thanks for your input.
