### ISSUE TITLE
Question regarding article

### ISSUE THREAD

**Issue by taori** [BorisTheBrave/mc-dc#4]
Sorry for bothering with the question. I hope it is okay to ask here since your blog has comments disabled.

First of all thanks a lot for all the effort you put into your very elaborate and comprehensive tutorial. So my question regarding the dual contouring article is the following:

How would i know the gradients to adapt the vertex of a cell without external information? In your sample this is known information because it is known by inferting the x and y of a cell and the distance from the center - but how would this work in a rendering scenario where i am unaware of the volume i am trying to render? 

I have looked at the implementation of lin20 but the code is not really optimized for comprehension, like your code , and i cannot yet comprehend how i would infer normals to adapt the vertex position in a scenario where i do not have information as to what exactly i am rendering.

Is there something i am missing or is that a case where i would just not adapt my vertex position at all (since getting normals would require external information)?

**Comment by BorisTheBrave** [comment]
Hi Taori, I have a discord you can join for non-issue questions.  https://discord.gg/Enzu2rrJFD

Dual Contouring needs gradient information. Like I said in the article, if you are starting from a known function, you can get the gradient from it using maths, or an approximation. It doesn't have to be a distance function, just anything that describes the volume. No further "external" information is needed.
