### ISSUE TITLE
A possible bug?

### ISSUE THREAD

**Issue by Sentient07** [BorisTheBrave/mc-dc#6]
https://github.com/BorisTheBrave/mc-dc/blob/a165b326849d8814fb03c963ad33a9faf6cc6dea/dual_contour_3d.py#L76 This line, it should be zmin, zmax, no?

**Comment by BorisTheBrave** [comment]
This looks like it's already fixed in master.

https://github.com/BorisTheBrave/mc-dc/commit/c28a6c7615b150aaf0a072921940fa8ba1e23a9f
