### ISSUE TITLE
Change of Resolution

### ISSUE THREAD

**Issue by csyhping** [BorisTheBrave/mc-dc#7]
Hi  @BorisTheBrave  , thanks for you amazing mc-dc tutorial. I'm new to marching cubes and really enjoyed your tutorial and code. I have a question, how can i modify the resolution of mc/dc? (i.e., change the grids resolution from 3*3*3 to 16*16*16) I tried to change XMIN/XMAX etc but the number of vertices always the same. Thanks!

**Comment by BorisTheBrave** [comment]
the cell size is hard coded as 1 in my code, for simplicity. you'd need to modify the code
There's two places that that really comes up:
`for x in range(xmin, xmax):`
this line (and similar) increases x by one each step, you'd want to change it to range(xmin, xmax, step_size)
`x1y1 = f(x + 1.0, y + 1.0)`
this line (and similar) evaluates f at a corner of the cube, so the +1 needs to be replaced with step_size

I'l consider improving this.

**Comment by lakshya-avataar** [comment]
Hi @BorisTheBrave 
Thank you for this amazing repository. I want to perform dual contouring on a point cloud data (I have SDF value for each point). What modifications (similar to what mentioned above) I should do to change resolution for dc?

**Comment by BorisTheBrave** [comment]
Making appropriate changes was harder than I thought, and it seems a sensible feature to add. 

So I've implemented it in cba2c8e7d87e6d2021b44e13e9ed7098e19be2bb...c30ea44c28d930f4994128e9bce532eaa92b1437. Hope that helps.

**Comment by csyhping** [comment]
Hi @BorisTheBrave , thanks for your quick help and modification! The new code seems all good but when I test with the [circle function, circle normal], there are some artifacts in the result .
![image](https://user-images.githubusercontent.com/38368516/235910268-e1f42244-c2f0-4f15-aa9d-ffdcee23a15b.png)

If I use [circle function, normal_from(circle function)], the result is better but still a flip face.
![image](https://user-images.githubusercontent.com/38368516/235912045-eb865071-6630-4fed-8625-6dadbd59f2d2.png)

Is it because the circal normal is not correct?

**Comment by csyhping** [comment]
> Hi @BorisTheBrave , thanks for your quick help and modification! The new code seems all good but when I test with the [circle function, circle normal], there are some artifacts in the result . ![image](https://user-images.githubusercontent.com/38368516/235910268-e1f42244-c2f0-4f15-aa9d-ffdcee23a15b.png)
> 
> If I use [circle function, normal_from(circle function)], the result is better but still a flip face. ![image](https://user-images.githubusercontent.com/38368516/235912045-eb865071-6630-4fed-8625-6dadbd59f2d2.png)
> 
> Is it because the circal normal is not correct?

I change CELL_SIZE to 0.1

**Comment by csyhping** [comment]
This is when i use CELL_SIZE 0.5, there are three artifaces areas. 
![image](https://user-images.githubusercontent.com/38368516/235913377-3d2a86b6-4917-4ddf-b0b5-8a94fb5ebf0c.png)

**Comment by BorisTheBrave** [comment]
I have addressed in https://github.com/BorisTheBrave/mc-dc/issues/8

**Comment by csyhping** [comment]
> I have addressed in #8

Thanks!
