### ISSUE TITLE
Artifacts with different CELL_SIZE

### ISSUE THREAD

**Issue by csyhping** [BorisTheBrave/mc-dc#8]
hi @BorisTheBrave , I think it maybe better to open a new issue to make it clearer. thanks for your quick help and modification! We'are able to change the resolution by CELL_SIZE now. The new code seems all good but when I test with the [circle function, circle normal], there are some artifacts in the result . 

CELL_SIZE = 0.1:
![image](https://user-images.githubusercontent.com/38368516/236084620-e1357f55-d3ed-4293-a685-d067c32d16e0.png)

If I use [circle function, normal_from(circle function)], the result is better but still a flip face.
![image](https://user-images.githubusercontent.com/38368516/236084648-70395a32-3faa-4ca0-a7d6-b827e5672a82.png)

This is when i use CELL_SIZE 0.5, there are three artifaces areas.
![image](https://user-images.githubusercontent.com/38368516/236084692-54a4dd6b-1e36-4c77-a482-986e5ed92aee.png)

Could you please help with this? Is it because the circal normal is not correct?

**Comment by BorisTheBrave** [comment]
Fixed, i forgot to update on section of code.

**Comment by csyhping** [comment]
> Fixed, i forgot to update on section of code.

Thanks!
