### ISSUE TITLE
What is the use of Quad.swap(bool)?

### ISSUE THREAD

**Issue by nvanfleet** [BorisTheBrave/mc-dc#9]
Hey there, I was trying to figure this out in another language, and I can't figure out what 

`Quad(Float, Float, Float, Float).swap(Bool)` is supposed to be doing.

reference:
https://github.com/BorisTheBrave/mc-dc/blob/a165b326849d8814fb03c963ad33a9faf6cc6dea/dual_contour_3d.py#L86

I get that there is a Quad object, which I believe is x, y, w, h. But I'm not sure what the `swap(bool)` function does. Is this flipping the face or something? Sorry I can't find documentation for utils3d anyplace so I don't really know where to go.

**Comment by BorisTheBrave** [comment]
Yes, it flips the face. I don't remember why i called it swap.
